name: Build Xamarin.iOS app

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Xamarin
      # You may pin to the exact commit or the version.
      # uses: maxim-lobanov/setup-xamarin@00b44a3ef9e2d1953010956de2022e8d095a196c
      uses: maxim-lobanov/setup-xamarin@v1

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore MyIosApp.sln
    - name: Build
      run: msbuild MyIosApp.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
      
    - name: ls
      run: |
           cd bin
           ls
